# GitLeaks Configuration
title = "GitLeaks config for vibe-coding"

[extend]
# path = "base-config.toml"

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api|token|secret|password)['"]*(?:\s*[:=]\s*|s*=\s*)['"]*([0-9a-zA-Z\-_\.]{20,})'''
keywords = [
    "api",
    "key",
    "token",
    "secret",
    "password",
]

[[rules]]
description = "Generic Secret"
id = "generic-secret"
regex = '''(?i)(?:secret)['"]*(?:\s*[:=]\s*|s*=\s*)['"]*([0-9a-zA-Z\-_\.]{10,})'''
keywords = [
    "secret",
]

[[rules]]
description = "AWS Access Key"
id = "aws-access-key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
keywords = [
    "aws",
]

[[rules]]
description = "GitHub Token"
id = "github-token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
keywords = [
    "github",
]

[[rules]]
description = "Google API Key"
id = "google-api-key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
keywords = [
    "google",
]

[[rules]]
description = "Stripe API Key"
id = "stripe-api-key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
keywords = [
    "stripe",
]

# Allowlist
[allowlist]
description = "Allowlisted files"
files = [
    '''package-lock\.json''',
    '''yarn\.lock''',
    '''\.env\.example''',
    '''\.env\.template''',
]

paths = [
    '''node_modules/''',
    '''.git/''',
    '''dist/''',
    '''build/''',
    '''.next/''',
    '''coverage/''',
]

regexes = [
    '''placeholder''',
    '''example''',
    '''test''',
    '''demo''',
    '''fake''',
    '''mock''',
]
